[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kickstarter = "DAqDXj2S1ipsGpe4eAi7AXBUT4MPd61DMDrq7QkvKUoY"

[programs.localnet]
kickstarter = "DAqDXj2S1ipsGpe4eAi7AXBUT4MPd61DMDrq7QkvKUoY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "demo-cli-local/fixtures/admin.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
